#!/usr/bin/env python3
"""
A2L 翻译工具 — 共享术语词典
================================
内建 1600+ 汽车行业中英德术语（含材料化学/法规排放/EV混动/ADAS/诊断通信/NVH/电气电子/功能安全/测试标定），基于有道词典/必应词典/CNKI翻译助手/COCA语料库/WordReference/欧路词典/金山词霸/爱词霸8大权威词典知识体系构建，供 GUI 和 CLI 共用。
"""

BUILTIN_GLOSSARY = {
    # ══════════════════════════════════════════════════════
    #  ECU 基础 / 结构术语
    # ══════════════════════════════════════════════════════
    "Engine Control Unit": "发动机控制单元",
    "Transmission Control Unit": "变速箱控制单元",
    "Engine Control Module": "发动机控制模块",
    "Body Control Module": "车身控制模块",
    "ABS Control Module": "ABS控制模块",
    "Airbag Control Module": "安全气囊控制模块",
    "Gateway Module": "网关模块",
    "Power Steering Control Module": "电动转向控制模块",
    "Instrument Cluster": "仪表盘",
    "Electronic Control Unit": "电控单元",
    "Calibration": "标定",
    "Measurement": "测量量",
    "Characteristic": "特性参数",
    "Parameters": "参数",
    "CompuMethod": "计算方法",
    "Function": "功能",
    "Group": "分组",
    "Axis": "轴",
    "Axis Points": "轴点",
    "Record Layout": "记录布局",
    "Module": "模块",
    "Header": "头部注释",
    "Comment": "注释",
    "Conversion": "转换",
    "Unit": "单位",
    "Display Identifier": "显示标识",
    "Address": "地址",
    "Data Type": "数据类型",
    "Byte Order": "字节序",
    "Deposit": "存储结构",
    "Bit Mask": "位掩码",
    "Bit Operation": "位操作",
    "Sign Extend": "符号扩展",
    "Extended Limits": "扩展极限",
    "Format": "格式",
    "Alignment": "对齐",
    "Memory Layout": "内存布局",
    "Memory Segment": "内存段",
    "EEPROM": "EEPROM",
    "Flash": "闪存",
    "RAM": "内存",
    "ROM": "只读存储器",
    "Read Only": "只读",
    "Read Write": "读写",
    "Virtual": "虚拟",
    "Structure": "结构",
    "Enumeration": "枚举",
    "Project": "项目",
    "Version": "版本",
    "Supplier": "供应商",
    "Customer": "客户",
    "Modification Date": "修改日期",
    "Naming Convention": "命名规范",

    # ══════════════════════════════════════════════════════
    #  传感器 (Sensors)
    # ══════════════════════════════════════════════════════
    "Engine Speed": "发动机转速",
    "Vehicle Speed": "车速",
    "Wheel Speed": "轮速",
    "Turbocharger Speed": "涡轮增压器转速",
    "Compressor Speed": "压气机转速",
    "Engine Speed Sensor": "发动机转速传感器",
    "Vehicle Speed Sensor": "车速传感器",
    "Crankshaft Position Sensor": "曲轴位置传感器",
    "Camshaft Position Sensor": "凸轮轴位置传感器",
    "Coolant Temperature": "冷却液温度",
    "Coolant Temperature Sensor": "冷却液温度传感器",
    "Intake Air Temperature": "进气温度",
    "Intake Air Temperature Sensor": "进气温度传感器",
    "Ambient Air Temperature": "环境温度",
    "Ambient Temperature": "环境温度",
    "Ambient Temperature Sensor": "环境温度传感器",
    "Ambient Pressure": "环境压力",
    "Ambient Pressure Sensor": "环境压力传感器",
    "Manifold Absolute Pressure": "进气歧管绝对压力",
    "Manifold Pressure": "进气歧管压力",
    "Manifold Pressure Sensor": "进气歧管压力传感器",
    "Absolute Pressure Sensor": "绝对压力传感器",
    "Barometric Pressure": "大气压力",
    "Barometric Pressure Sensor": "大气压力传感器",
    "Fuel Pressure": "燃油压力",
    "Fuel Pressure Sensor": "燃油压力传感器",
    "Fuel Rail Pressure": "共轨压力",
    "Fuel Rail Pressure Sensor": "共轨压力传感器",
    "Oil Pressure": "机油压力",
    "Oil Pressure Sensor": "机油压力传感器",
    "Oil Temperature": "机油温度",
    "Oil Temperature Sensor": "机油温度传感器",
    "Fuel Temperature": "燃油温度",
    "Fuel Temperature Sensor": "燃油温度传感器",
    "Exhaust Gas Temperature": "排气温度",
    "Exhaust Temperature Sensor": "排气温度传感器",
    "Exhaust Gas Pressure": "排气压力",
    "Exhaust Back Pressure": "排气背压",
    "Exhaust Pressure Sensor": "排气压力传感器",
    "Battery Voltage": "电池电压",
    "System Voltage": "系统电压",
    "Supply Voltage": "供电电压",
    "Reference Voltage": "参考电压",
    "Voltage Sensor": "电压传感器",
    "Current Sensor": "电流传感器",
    "Throttle Position": "节气门位置",
    "Throttle Position Sensor": "节气门位置传感器",
    "Accelerator Pedal Position": "油门踏板位置",
    "Accelerator Pedal Sensor": "油门踏板位置传感器",
    "Clutch Pedal Position": "离合器踏板位置",
    "Clutch Position Sensor": "离合器位置传感器",
    "Brake Pedal Position": "制动踏板位置",
    "Brake Pedal Switch": "制动踏板开关",
    "Brake Light Switch": "制动灯开关",
    "Steering Angle": "转向角度",
    "Steering Angle Sensor": "转向角度传感器",
    "Steering Wheel Angle": "方向盘角度",
    "Steering Torque": "转向力矩",
    "Yaw Rate": "横摆角速度",
    "Yaw Rate Sensor": "横摆角速度传感器",
    "Lateral Acceleration": "侧向加速度",
    "Longitudinal Acceleration": "纵向加速度",
    "Acceleration Sensor": "加速度传感器",
    "Mass Air Flow": "空气质量流量",
    "Air Mass Flow": "空气质量流量",
    "Mass Air Flow Sensor": "空气质量流量传感器",
    "Fuel Mass Flow": "燃油质量流量",
    "Injection Quantity": "喷油量",
    "Injection Timing": "喷油正时",
    "Ignition Timing": "点火正时",
    "Ignition Advance": "点火提前角",
    "Spark Advance": "点火提前角",
    "Dwell Time": "闭合角时间",
    "Oxygen Sensor": "氧传感器",
    "O2 Sensor": "氧传感器",
    "Wideband Oxygen Sensor": "宽带氧传感器",
    "Lambda Sensor": "Lambda传感器",
    "Lambda Value": "Lambda 值",
    "Lambda Setpoint": "Lambda 目标值",
    "Lambda Control": "Lambda 控制",
    "Lambda Controller": "Lambda控制器",
    "Knock Sensor": "爆震传感器",
    "Knock Detection": "爆震检测",
    "Knock Control": "爆震控制",
    "Knock Window": "爆震窗口",
    "Crankshaft Position": "曲轴位置",
    "Camshaft Position": "凸轮轴位置",
    "Camshaft Phase": "凸轮轴相位",
    "Cylinder Pressure": "缸内压力",
    "Cylinder Pressure Sensor": "缸内压力传感器",
    "Misfire Detection": "失火检测",
    "Rough Road Detection": "坏路检测",
    "Rain Sensor": "雨量传感器",
    "Light Sensor": "光照传感器",
    "Humidity Sensor": "湿度传感器",
    "Air Quality Sensor": "空气质量传感器",
    "NOx Sensor": "NOx传感器",
    "PM Sensor": "颗粒物传感器",
    "Differential Pressure Sensor": "差压传感器",
    "Tank Pressure Sensor": "油箱压力传感器",
    "Refrigerant Pressure Sensor": "冷媒压力传感器",
    "Fuel Level Sensor": "燃油液位传感器",
    "Gear Position Sensor": "档位传感器",
    "Parking Brake Switch": "驻车制动开关",
    "Seat Occupancy Sensor": "座椅占用传感器",
    "Windscreen Temperature": "风挡温度",

    # ══════════════════════════════════════════════════════
    #  执行器 (Actuators)
    # ══════════════════════════════════════════════════════
    "Throttle Actuator": "节气门执行器",
    "Electronic Throttle Control": "电子节气门控制",
    "EGR Actuator": "EGR执行器",
    "Wastegate Actuator": "废气旁通阀执行器",
    "VVT Actuator": "VVT执行器",
    "VVT Solenoid": "VVT电磁阀",
    "Fuel Injector": "喷油器",
    "Fuel Pump": "燃油泵",
    "Fuel Pump Module": "燃油泵模块",
    "High Pressure Pump": "高压油泵",
    "Low Pressure Pump": "低压油泵",
    "Ignition Coil": "点火线圈",
    "Spark Plug": "火花塞",
    "Idle Air Control": "怠速空气控制",
    "Idle Air Control Valve": "怠速空气控制阀",
    "Purge Valve": "碳罐电磁阀",
    "Canister Purge Valve": "碳罐清洗阀",
    "Coolant Pump": "冷却液泵",
    "Electric Coolant Pump": "电子冷却液泵",
    "Thermostat": "节温器",
    "Electric Thermostat": "电子节温器",
    "Radiator Fan": "散热器风扇",
    "Cooling Fan": "冷却风扇",
    "Intake Manifold Runner Control": "进气歧管翻板控制",
    "Swirl Flap": "涡流翻板",
    "Tumble Flap": "滚流翻板",
    "Variable Intake Manifold": "可变进气歧管",
    "Exhaust Flap": "排气翻板",
    "Electric Exhaust Flap": "电动排气翻板",
    "Alternator": "发电机",
    "Starter": "起动机",
    "Starter Relay": "起动机继电器",
    "Main Relay": "主继电器",
    "Fuel Pump Relay": "燃油泵继电器",
    "Transmission Solenoid": "变速箱电磁阀",
    "Shift Solenoid": "换挡电磁阀",
    "Torque Converter Clutch": "变矩器锁止离合器",
    "Clutch Actuator": "离合器执行器",
    "Gear Actuator": "换挡执行器",
    "Brake Actuator": "制动执行器",
    "ABS Pump": "ABS泵",
    "ABS Valve": "ABS阀",
    "ESP Valve": "ESP阀",
    "Vacuum Pump": "真空泵",
    "Horn": "喇叭",

    # ══════════════════════════════════════════════════════
    #  进气 / 增压系统
    # ══════════════════════════════════════════════════════
    "Boost Pressure": "增压压力",
    "Boost Pressure Setpoint": "增压压力目标值",
    "Boost Pressure Actual": "增压压力实际值",
    "Boost Pressure Control": "增压压力控制",
    "Turbocharger": "涡轮增压器",
    "Supercharger": "机械增压器",
    "Twin Turbo": "双涡轮",
    "Variable Geometry Turbo": "可变截面涡轮",
    "Wastegate Position": "废气旁通阀位置",
    "Wastegate Duty Cycle": "废气旁通阀占空比",
    "Wastegate Control": "废气旁通阀控制",
    "Diverter Valve": "泄压阀",
    "Blow Off Valve": "放气阀",
    "Recirculation Valve": "回流阀",
    "Charge Air Cooler": "中冷器",
    "Intercooler": "中冷器",
    "Charge Air Temperature": "增压空气温度",
    "Charge Air Pressure": "增压空气压力",
    "Intake Air Mass": "进气量",
    "Intake Air Flow": "进气流速",
    "Volumetric Efficiency": "充气效率",
    "Intake Manifold": "进气歧管",
    "Intake Runner": "进气道",
    "Air Cleaner": "空滤器",
    "Air Filter": "空气滤清器",
    "Throttle Body": "节气门体",
    "Throttle Plate": "节气门翻板",
    "Throttle Area": "节气门面积",
    "Air Bypass Valve": "空气旁通阀",

    # ══════════════════════════════════════════════════════
    #  燃油系统
    # ══════════════════════════════════════════════════════
    "Fuel Injection": "燃油喷射",
    "Direct Injection": "缸内直喷",
    "Port Injection": "进气道喷射",
    "Multi Point Injection": "多点喷射",
    "Sequential Injection": "顺序喷射",
    "Injection Duration": "喷油脉宽",
    "Injection Angle": "喷油角度",
    "Injection Mode": "喷射模式",
    "Start of Injection": "喷油始点",
    "End of Injection": "喷油终点",
    "Post Injection": "后喷",
    "Pilot Injection": "预喷",
    "Main Injection": "主喷",
    "Multiple Injection": "多次喷射",
    "Fuel Rail": "共轨",
    "Rail Pressure Setpoint": "共轨压力目标值",
    "Rail Pressure Control": "共轨压力控制",
    "Fuel Pressure Regulator": "燃油压力调节器",
    "Fuel Cutoff": "断油",
    "Deceleration Fuel Cutoff": "减速断油",
    "Overrun Fuel Cutoff": "超速断油",
    "Fuel Cut On": "恢复供油",
    "Fuel Trim": "燃油修正",
    "Short Term Fuel Trim": "短期燃油修正",
    "Long Term Fuel Trim": "长期燃油修正",
    "Fuel Adaptation": "燃油自适应",
    "Fuel Consumption": "油耗",
    "Fuel Economy": "燃油经济性",
    "Fuel Level": "燃油液位",
    "Fuel Tank": "油箱",
    "Fuel Tank Vent": "油箱通风",
    "Evaporative System": "蒸发排放系统",
    "EVAP Purge": "碳罐清洗",
    "Fuel Pump Control": "燃油泵控制",
    "Fuel Pump Duty": "燃油泵占空比",

    # ══════════════════════════════════════════════════════
    #  点火系统
    # ══════════════════════════════════════════════════════
    "Ignition System": "点火系统",
    "Ignition Coil Charge Time": "点火线圈充电时间",
    "Ignition Dwell": "点火闭合角",
    "Ignition Angle": "点火角",
    "Base Ignition": "基础点火",
    "Base Timing": "基础正时",
    "Ignition Map": "点火图",
    "Ignition Timing Map": "点火正时图",
    "Timing Map": "正时图",
    "Ignition Cutoff": "断火",
    "Spark Duration": "火花持续时间",
    "Spark Energy": "火花能量",
    "Cylinder Identification": "缸判别",
    "Synchronization": "同步",
    "Engine Phase": "发动机相位",
    "Ignition Output": "点火输出",
    "Ignition Coil Driver": "点火线圈驱动",

    # ══════════════════════════════════════════════════════
    #  排气 / 排放系统
    # ══════════════════════════════════════════════════════
    "Exhaust Gas Recirculation": "废气再循环",
    "EGR Valve Position": "EGR 阀位置",
    "EGR Rate": "EGR 率",
    "EGR Cooler": "EGR冷却器",
    "EGR Temperature": "EGR温度",
    "EGR Control": "EGR控制",
    "High Pressure EGR": "高压EGR",
    "Low Pressure EGR": "低压EGR",
    "Catalyst Temperature": "催化器温度",
    "Catalyst Heating": "催化器加热",
    "Catalyst Model": "催化器模型",
    "Catalyst Conversion": "催化器转化效率",
    "Three Way Catalyst": "三元催化器",
    "TWC Temperature": "三元催化器温度",
    "Selective Catalytic Reduction": "选择性催化还原",
    "SCR System": "SCR系统",
    "SCR Temperature": "SCR温度",
    "AdBlue": "尿素",
    "AdBlue Tank Level": "尿素液位",
    "AdBlue Dosing": "尿素喷射",
    "Diesel Particulate Filter": "柴油颗粒捕集器",
    "DPF Soot Load": "DPF碳载量",
    "DPF Regeneration": "DPF再生",
    "DPF Temperature": "DPF温度",
    "DPF Pressure Drop": "DPF压差",
    "Oxidation Catalyst": "氧化催化器",
    "Exhaust Manifold": "排气歧管",
    "Exhaust Valve": "排气门",
    "Secondary Air Injection": "二次空气喷射",
    "Secondary Air Pump": "二次空气泵",
    "Oxygen Sensor Heater": "氧传感器加热",
    "Lambda Heater": "Lambda加热",
    "Oxygen Storage Capacity": "储氧量",
    "OBD": "车载诊断",
    "OBD II": "OBD II",
    "EOBD": "欧洲车载诊断",
    "Malfunction Indicator": "故障指示灯",
    "Check Engine": "检查发动机",
    "Diagnostic Trouble Code": "诊断故障码",
    "Fault Code": "故障码",
    "P Code": "P码",
    "U Code": "U码",
    "Monitor": "监控器",
    "Readiness": "就绪状态",
    "Diagnostic": "诊断",
    "Error Detection": "错误检测",
    "Debounce": "防抖",
    "Signal Range Check": "信号范围检查",
    "Plausibility Check": "合理性检查",
    "Rationality Check": "合理性检查",
    "Electrical Check": "电气检查",
    "Short to Ground": "对地短路",
    "Short to Battery": "对电源短路",
    "Open Circuit": "断路",
    "Open Load": "开路",

    # ══════════════════════════════════════════════════════
    #  扭矩 / 负荷管理
    # ══════════════════════════════════════════════════════
    "Torque": "扭矩",
    "Engine Torque": "发动机扭矩",
    "Torque Model": "扭矩模型",
    "Indicated Torque": "指示扭矩",
    "Actual Torque": "实际扭矩",
    "Target Torque": "目标扭矩",
    "Requested Torque": "请求扭矩",
    "Driver Demand Torque": "驾驶员需求扭矩",
    "Friction Torque": "摩擦扭矩",
    "Pumping Torque": "泵气扭矩",
    "Torque Limitation": "扭矩限制",
    "Torque Reserve": "扭矩储备",
    "Torque Intervention": "扭矩干预",
    "Torque Coordination": "扭矩协调",
    "Torque Monitoring": "扭矩监控",
    "Maximum Torque": "最大扭矩",
    "Minimum Torque": "最小扭矩",
    "Engine Load": "发动机负荷",
    "Relative Load": "相对负荷",
    "Absolute Load": "绝对负荷",
    "Load Signal": "负荷信号",
    "Calculated Load": "计算负荷",
    "Pedal Map": "踏板特性",
    "Pedal Characteristic": "踏板特性曲线",
    "Driver Wish": "驾驶员意图",
    "Tip In": "急加速",
    "Tip Out": "急减速",
    "Acceleration Enrichment": "加速加浓",
    "Deceleration Enleanment": "减速减稀",
    "Dashpot": "缓冲",
    "Anti Jerk": "防闯动",

    # ══════════════════════════════════════════════════════
    #  怠速控制
    # ══════════════════════════════════════════════════════
    "Idle Speed": "怠速转速",
    "Idle Speed Target": "怠速目标转速",
    "Idle Control": "怠速控制",
    "Idle Governor": "怠速调节器",
    "Idle Calibration": "怠速标定",
    "Target Idle": "目标怠速",
    "Idle Actuator": "怠速执行器",
    "Idle Air": "怠速空气",
    "Idle Spark": "怠速点火",
    "Idle Torque Reserve": "怠速扭矩储备",
    "Idle Speed Fluctuation": "怠速波动",
    "Fast Idle": "快怠速",
    "Cold Idle": "冷机怠速",
    "Warm Idle": "暖机怠速",
    "Idle Up": "怠速提升",
    "Power Steering Idle Up": "转向怠速提升",
    "AC Idle Up": "空调怠速提升",
    "Electrical Load Idle Up": "电气负载怠速提升",

    # ══════════════════════════════════════════════════════
    #  气门 / VVT
    # ══════════════════════════════════════════════════════
    "Variable Valve Timing": "可变气门正时",
    "Variable Valve Lift": "可变气门升程",
    "VVT Angle": "VVT 角度",
    "VVT Position": "VVT位置",
    "VVT Target": "VVT目标",
    "VVT Duty Cycle": "VVT占空比",
    "Intake VVT": "进气VVT",
    "Exhaust VVT": "排气VVT",
    "Valve Timing": "气门正时",
    "Valve Lift": "气门升程",
    "Valve Overlap": "气门重叠",
    "Valve Duration": "气门持续期",
    "Camshaft": "凸轮轴",
    "Intake Camshaft": "进气凸轮轴",
    "Exhaust Camshaft": "排气凸轮轴",
    "Cam Profile": "凸轮型线",
    "Phaser": "调相器",
    "Oil Control Valve": "机油控制阀",
    "Cylinder Deactivation": "闭缸",
    "Half Engine Mode": "半缸模式",

    # ══════════════════════════════════════════════════════
    #  变速箱
    # ══════════════════════════════════════════════════════
    "Transmission": "变速箱",
    "Automatic Transmission": "自动变速箱",
    "Manual Transmission": "手动变速箱",
    "Dual Clutch Transmission": "双离合变速箱",
    "Continuously Variable Transmission": "无级变速箱",
    "CVT": "CVT",
    "DCT": "DCT",
    "AT": "AT",
    "MT": "MT",
    "Shift Schedule": "换挡策略",
    "Shift Point": "换挡点",
    "Shift Time": "换挡时间",
    "Shift Quality": "换挡品质",
    "Shift Fork": "换挡拨叉",
    "Shift Drum": "换挡鼓",
    "Gear Ratio": "传动比",
    "Gear": "档位",
    "Gear Position": "档位",
    "Current Gear": "当前档位",
    "Target Gear": "目标档位",
    "Neutral": "空档",
    "Park": "驻车",
    "Reverse": "倒档",
    "Drive": "前进",
    "Sport Mode": "运动模式",
    "Economy Mode": "经济模式",
    "Manual Mode": "手动模式",
    "Kick Down": "强制降档",
    "Downshift": "降档",
    "Upshift": "升档",
    "Skip Shift": "跳档",
    "Transmission Fluid Temperature": "变速箱油温",
    "Transmission Oil": "变速箱油",
    "Torque Converter": "变矩器",
    "Torque Converter Slip": "变矩器滑差",
    "Torque Converter Lockup": "变矩器锁止",
    "Clutch Control": "离合器控制",
    "Clutch Adaptation": "离合器自适应",
    "Clutch Wear": "离合器磨损",
    "Creep": "蠕行",
    "Hill Holder": "坡道保持",
    "Launch Control": "弹射起步",

    # ══════════════════════════════════════════════════════
    #  混合动力 / 电动
    # ══════════════════════════════════════════════════════
    "Hybrid": "混合动力",
    "Hybrid Control Unit": "混合动力控制单元",
    "Electric Motor": "电机",
    "Motor Control": "电机控制",
    "Motor Torque": "电机扭矩",
    "Motor Speed": "电机转速",
    "Motor Temperature": "电机温度",
    "Motor Current": "电机电流",
    "Inverter": "逆变器",
    "Inverter Temperature": "逆变器温度",
    "DC DC Converter": "DC-DC转换器",
    "High Voltage Battery": "高压电池",
    "Battery Management System": "电池管理系统",
    "Battery State of Charge": "电池SOC",
    "Battery SOC": "电池SOC",
    "State of Charge": "荷电状态",
    "Battery State of Health": "电池SOH",
    "State of Health": "健康状态",
    "Battery Temperature": "电池温度",
    "Battery Voltage": "电池电压",
    "Battery Current": "电池电流",
    "Cell Voltage": "单体电压",
    "Cell Temperature": "单体温度",
    "Charge Mode": "充电模式",
    "Discharge Mode": "放电模式",
    "Regenerative Braking": "再生制动",
    "Regen Brake": "回馈制动",
    "Regeneration Level": "回馈等级",
    "Coasting": "滑行",
    "Electric Driving": "纯电行驶",
    "Range Extender": "增程器",
    "EV Mode": "纯电模式",
    "Hybrid Mode": "混动模式",
    "Engine On Request": "发动机启动请求",
    "Engine Off Request": "发动机关闭请求",
    "Start Stop": "启停",
    "Auto Start Stop": "自动启停",
    "Stop Prevent": "禁止停机",
    "Start Request": "启动请求",
    "Onboard Charger": "车载充电机",
    "Charging": "充电",
    "Fast Charging": "快充",
    "Slow Charging": "慢充",
    "Charging Port": "充电口",
    "Drive Motor": "驱动电机",
    "Permanent Magnet Motor": "永磁电机",
    "Induction Motor": "感应电机",
    "Traction Motor": "牵引电机",
    "Electric Drive": "电驱动",

    # ══════════════════════════════════════════════════════
    #  底盘 / 制动 / 转向
    # ══════════════════════════════════════════════════════
    "ABS": "防抱死制动",
    "Anti Lock Braking": "防抱死制动",
    "Electronic Stability Program": "电子稳定程序",
    "ESP": "ESP",
    "ESC": "ESC",
    "Traction Control": "牵引力控制",
    "Brake Assist": "制动辅助",
    "Brake Booster": "制动助力器",
    "Electric Brake Booster": "电子制动助力器",
    "Brake Vacuum": "制动真空度",
    "Brake Pressure": "制动压力",
    "Brake Fluid": "制动液",
    "Brake Disc Temperature": "制动盘温度",
    "Brake Pad Wear": "制动片磨损",
    "Brake Override": "制动优先",
    "Electric Parking Brake": "电子驻车制动",
    "Electric Parking Brake": "电子驻车制动",
    "Parking Brake": "驻车制动",
    "Auto Hold": "自动驻车",
    "Power Steering": "动力转向",
    "Electric Power Steering": "电动助力转向",
    "Hydraulic Power Steering": "液压助力转向",
    "Steering Assist": "转向助力",
    "Steering Rack": "转向齿条",
    "Steering Column": "转向柱",
    "Steering Feel": "转向手感",
    "Active Steering": "主动转向",
    "Rear Wheel Steering": "后轮转向",
    "Suspension Control": "悬架控制",
    "Active Suspension": "主动悬架",
    "Air Suspension": "空气悬架",
    "Adaptive Damping": "自适应减震",
    "Damping Control": "减震控制",
    "Ride Height": "车身高度",
    "Tire Pressure Monitoring": "胎压监测",
    "TPMS": "TPMS",
    "Tire Pressure": "胎压",
    "Wheel Alignment": "车轮定位",
    "Chassis Control": "底盘控制",
    "Vehicle Dynamics": "车辆动力学",

    # ══════════════════════════════════════════════════════
    #  ADAS / 安全 / 驾驶辅助
    # ══════════════════════════════════════════════════════
    "Adaptive Cruise Control": "自适应巡航",
    "Cruise Control": "巡航控制",
    "Speed Limiter": "限速器",
    "Lane Departure Warning": "车道偏离预警",
    "Lane Keeping Assist": "车道保持辅助",
    "Lane Centering": "车道居中",
    "Blind Spot Detection": "盲区检测",
    "Blind Spot Warning": "盲区预警",
    "Forward Collision Warning": "前碰撞预警",
    "Automatic Emergency Braking": "自动紧急制动",
    "Collision Mitigation": "碰撞缓解",
    "Pedestrian Detection": "行人检测",
    "Traffic Sign Recognition": "交通标志识别",
    "Driver Monitoring": "驾驶员监控",
    "Driver Drowsiness": "驾驶员疲劳",
    "Attention Assist": "注意力辅助",
    "Park Assist": "泊车辅助",
    "Parking Sensor": "泊车传感器",
    "Ultrasonic Sensor": "超声波传感器",
    "Radar": "雷达",
    "Front Radar": "前雷达",
    "Rear Radar": "后雷达",
    "Lidar": "激光雷达",
    "Camera": "摄像头",
    "Front Camera": "前摄像头",
    "Surround View": "全景影像",
    "Night Vision": "夜视",
    "Airbag": "安全气囊",
    "Airbag Deployment": "安全气囊触发",
    "Seat Belt": "安全带",
    "Seat Belt Reminder": "安全带提醒",
    "Rollover Detection": "翻滚检测",
    "Crash Detection": "碰撞检测",
    "Safety Limitation": "安全限制",
    "Safety Shutdown": "安全关闭",
    "Functional Safety": "功能安全",
    "Watchdog": "看门狗",
    "Protection": "保护",
    "Override": "超控",
    "Fail Safe": "故障安全",
    "Limp Home": "跛行回家",
    "Emergency Mode": "应急模式",

    # ══════════════════════════════════════════════════════
    #  车身 / 舒适 / 空调
    # ══════════════════════════════════════════════════════
    "Body Control": "车身控制",
    "Central Locking": "中控锁",
    "Door Lock": "门锁",
    "Door Module": "车门模块",
    "Window Lift": "车窗升降",
    "Power Window": "电动车窗",
    "Sunroof": "天窗",
    "Mirror": "后视镜",
    "Mirror Folding": "后视镜折叠",
    "Mirror Heating": "后视镜加热",
    "Light Control": "灯光控制",
    "Headlight": "前照灯",
    "Daytime Running Light": "日间行车灯",
    "Turn Signal": "转向灯",
    "Fog Light": "雾灯",
    "High Beam": "远光",
    "Low Beam": "近光",
    "Automatic Light": "自动灯光",
    "Ambient Light": "氛围灯",
    "Wiper": "雨刮",
    "Rain Sensing Wiper": "雨量感应雨刮",
    "Window Washer": "玻璃洗涤",
    "Heated Window": "加热玻璃",
    "Heated Seat": "加热座椅",
    "Seat Control": "座椅控制",
    "Seat Memory": "座椅记忆",
    "Lumbar Support": "腰部支撑",
    "Massage Seat": "按摩座椅",
    "Climate Control": "空调控制",
    "Air Conditioning": "空调",
    "Automatic Climate": "自动空调",
    "AC Compressor": "空调压缩机",
    "AC Clutch": "空调离合器",
    "AC Pressure": "空调压力",
    "AC Request": "空调请求",
    "Evaporator Temperature": "蒸发器温度",
    "Blower Motor": "鼓风机",
    "Heater Core": "暖风芯体",
    "Air Distribution": "风门分配",
    "Recirculation": "内循环",
    "Fresh Air": "外循环",
    "Defrost": "除霜",

    # ══════════════════════════════════════════════════════
    #  通信 / 网络
    # ══════════════════════════════════════════════════════
    "CAN Bus": "CAN总线",
    "CAN Message": "CAN报文",
    "CAN ID": "CAN ID",
    "CAN Frame": "CAN帧",
    "CAN Network": "CAN网络",
    "CAN Transceiver": "CAN收发器",
    "LIN Bus": "LIN总线",
    "FlexRay": "FlexRay",
    "Ethernet": "车载以太网",
    "Gateway": "网关",
    "Network Management": "网络管理",
    "Bus Off": "总线关闭",
    "Bus Load": "总线负载",
    "Node": "节点",
    "Signal": "信号",
    "Signal Group": "信号组",
    "Message": "报文",
    "PDU": "协议数据单元",
    "Frame": "帧",
    "Checksum": "校验和",
    "CRC": "CRC校验",
    "Rolling Counter": "滚动计数器",
    "Timeout": "超时",
    "Timeout Error": "超时错误",

    # ══════════════════════════════════════════════════════
    #  校准 / 标定相关
    # ══════════════════════════════════════════════════════
    "ECU Calibration": "ECU 标定",
    "Control Unit Calibration": "控制单元标定",
    "Control Module": "控制模块",
    "Engine Control": "发动机控制",
    "Closed-loop": "闭环",
    "Open-loop": "开环",
    "Closed Loop": "闭环",
    "Open Loop": "开环",
    "Fuel Control": "燃油控制",
    "Oxygen Sensor Feedback": "氧传感器反馈",
    "Sensor Measurement": "传感器测量",
    "Sensor Measurements": "传感器测量",
    "All Sensor": "全部传感器",
    "All Sensor Measurements": "全部传感器测量",
    "Lookup Table": "查找表",
    "Map": "图",
    "Curve": "曲线",
    "Table": "表",
    "Axis Points": "轴点",
    "Breakpoints": "断点",
    "Interpolation": "插值",
    "Linear Interpolation": "线性插值",
    "Polynomial": "多项式",
    "Coefficient": "系数",
    "Formula": "公式",
    "Rational Function": "有理函数",
    "Conversion Table": "转换表",
    "Lookup": "查表",
    "Speed Conversion": "速度转换",
    "Speed Enum": "速度枚举",
    "Common Parameters": "通用参数",
    "Common Calibration": "通用标定",
    "Calibration Data": "标定数据",
    "Calibration File": "标定文件",
    "Checksum Correction": "校验和修正",
    "Fingerprint": "指纹",
    "Seed Key": "种子密钥",
    "Security Access": "安全访问",
    "Unlock": "解锁",
    "Programming": "编程",
    "Flash Programming": "闪存编程",
    "Bootloader": "引导加载程序",
    "Application Software": "应用软件",

    # ══════════════════════════════════════════════════════
    #  加工 / 信号处理
    # ══════════════════════════════════════════════════════
    "Signal Processing": "信号处理",
    "Filter": "滤波器",
    "Low Pass Filter": "低通滤波",
    "High Pass Filter": "高通滤波",
    "Band Pass Filter": "带通滤波",
    "Filter Coefficient": "滤波系数",
    "Filter Time Constant": "滤波时间常数",
    "Time Constant": "时间常数",
    "Smoothing": "平滑",
    "Averaging": "平均",
    "Moving Average": "滑动平均",
    "Rate Limiter": "速率限制器",
    "Ramp": "斜坡",
    "Gradient": "梯度",
    "Dead Time": "死区时间",
    "Dead Band": "死区",
    "Hysteresis": "迟滞",
    "Resolution": "分辨率",
    "Accuracy": "精度",
    "Sampling": "采样",
    "Sample Rate": "采样率",
    "Sampling Time": "采样时间",
    "Quantization": "量化",
    "Noise": "噪声",
    "Signal to Noise Ratio": "信噪比",
    "Offset": "偏移",
    "Gain": "增益",
    "Calibration Factor": "校准因子",
    "Sensor Characteristic": "传感器特性",
    "Transfer Function": "传递函数",
    "Linearization": "线性化",
    "Analog": "模拟",
    "Digital": "数字",
    "Analog to Digital": "模数转换",
    "Digital to Analog": "数模转换",
    "PWM": "PWM",
    "Duty Cycle": "占空比",
    "Frequency": "频率",
    "Pulse Width": "脉冲宽度",
    "Counter": "计数器",
    "Timer": "定时器",

    # ══════════════════════════════════════════════════════
    #  系统状态 / 工作模式
    # ══════════════════════════════════════════════════════
    "Power On": "上电",
    "Power Off": "下电",
    "Ignition On": "点火ON",
    "Ignition Off": "点火OFF",
    "Engine Running": "发动机运行",
    "Engine Cranking": "发动机起动",
    "Engine Stopped": "发动机停止",
    "Warm Up": "暖机",
    "Cold Start": "冷启动",
    "Hot Start": "热启动",
    "Normal Operation": "正常运行",
    "Fault State": "故障状态",
    "Degraded Mode": "降级模式",
    "Sleep Mode": "休眠模式",
    "Wakeup": "唤醒",
    "Shutdown": "关机",
    "Reset": "复位",
    "Initialization": "初始化",
    "Self Test": "自检",
    "Calibration Mode": "标定模式",
    "Service Mode": "服务模式",
    "Transport Mode": "运输模式",
    "Factory Mode": "工厂模式",
    "End of Line": "下线",
    "Power Down": "掉电",
    "After Run": "后运行",
    "Pre Drive": "预驱动",
    "Post Drive": "后驱动",

    # ══════════════════════════════════════════════════════
    #  冷却 / 热管理
    # ══════════════════════════════════════════════════════
    "Cooling System": "冷却系统",
    "Thermal Management": "热管理",
    "Radiator": "散热器",
    "Coolant": "冷却液",
    "Coolant Level": "冷却液液位",
    "Coolant Flow": "冷却液流量",
    "Coolant Pump Control": "冷却液泵控制",
    "Fan Control": "风扇控制",
    "Fan Speed": "风扇转速",
    "Fan Duty": "风扇占空比",
    "Grille Shutter": "格栅百叶窗",
    "Active Grille Shutter": "主动式格栅",
    "Oil Cooler": "机油冷却器",
    "Transmission Cooler": "变速箱冷却器",
    "Heat Exchanger": "热交换器",

    # ══════════════════════════════════════════════════════
    #  通用技术术语 / 复合短语
    # ══════════════════════════════════════════════════════
    "Turbo Engine": "涡轮发动机",
    "Main Engine": "主发动机",
    "Sensor Group": "传感器组",
    "RPM Axis": "转速轴",
    "Engine RPM": "发动机转速",
    "Voltage Monitoring": "电压监控",
    "Voltage Measurement": "电压测量",
    "Current Measurement": "电流测量",
    "Current Monitoring": "电流监控",
    "Temperature Monitoring": "温度监控",
    "Pressure Monitoring": "压力监控",
    "Speed Control": "转速控制",
    "Speed Limitation": "转速限制",
    "Speed Governor": "调速器",
    "Anti Stall": "防熄火",
    "Stall Detection": "熄火检测",
    "Stall Prevention": "熄火预防",
    "Engine Braking": "发动机制动",
    "Compression Brake": "压缩制动",
    "Exhaust Brake": "排气制动",
    "Cruise": "巡航",
    "Idle Speed Control": "怠速转速控制",
    "Engine Speed Control": "发动机转速控制",
    "Speed Density": "速度密度法",
    "Alpha N": "Alpha-N",
    "Torque Structure": "扭矩结构",
    "Engine Model": "发动机模型",
    "Air Model": "空气模型",
    "Fuel Model": "燃油模型",
    "Wall Wetting": "油膜",
    "Wall Film": "油膜",
    "Fuel Film": "油膜",
    "Puddle": "油膜",
    "Evaporation": "蒸发",
    "Condensation": "冷凝",
    "Vapor Pressure": "蒸汽压力",
    "Saturation": "饱和",
    "Injection Timing Calculation": "喷油正时计算",
    "Start Ability": "起动性能",
    "Hot Restart": "热重启",
    "Maximum": "最大值",
    "Minimum": "最小值",
    "Threshold": "阈值",
    "Limit": "限制",
    "Limitation": "限制",
    "Window": "窗口",
    "Range": "范围",
    "Delay": "延迟",
    "Time": "时间",
    "Rate": "率",
    "Ratio": "比值",
    "Factor": "因子",
    "Multiplier": "乘数",
    "Constant": "常数",
    "Parameter": "参数",
    "Setpoint": "目标值",
    "Actual": "实际值",
    "Set": "设定值",
    "Raw": "原始值",
    "Physical": "物理值",
    "Normalized": "归一化值",
    "Enable": "使能",
    "Disable": "禁止",
    "Activate": "激活",
    "Deactivate": "停用",
    "Status": "状态",
    "State": "状态",
    "Control": "控制",
    "Mode": "模式",
    "Type": "类型",
    "Index": "索引",
    "ID": "ID",
    "Number": "编号",
    "Count": "计数",
    "Value": "值",
    "Level": "水平",
    "Percentage": "百分比",
    "Percent": "%",
    "Low": "低",
    "Medium": "中",
    "High": "高",
    "Normal": "正常",
    "Abnormal": "异常",
    "Valid": "有效",
    "Invalid": "无效",
    "Active": "激活",
    "Inactive": "未激活",
    "Default": "默认",
    "Nominal": "标称",
    "Reference": "参考",
    "Measured": "实测",
    "Estimated": "估算",
    "Calculated": "计算",
    "Predicted": "预测",
    "Adaptation": "自适应",
    "Correction": "修正",
    "Compensation": "补偿",
    "Adjustment": "调整",
    "Learning": "学习",
    "Monitoring": "监控",
    "Supervision": "监控",
    "Detection": "检测",
    "Recognition": "识别",
    "Comparison": "比较",
    "Calculation": "计算",
    "Evaluation": "评估",
    "Estimation": "估计",
    "Prediction": "预测",
    "Simulation": "模拟",
    "Validation": "验证",
    "Verification": "校验",
    "Authorization": "授权",
    "Configuration": "配置",
    "Main": "主",
    "Auxiliary": "辅助",
    "Primary": "主要",
    "Secondary": "次要",
    "Backup": "备用",
    "Safety": "安全",
    "Redundant": "冗余",
    "Main Engine": "主发动机",
    "Turbo Engine": "涡轮发动机",
    "Pressure Sensor": "压力传感器",
    "Temperature Sensor": "温度传感器",
    "Speed Sensor": "速度传感器",
    "Position Sensor": "位置传感器",
    "Engine Speed Sensor": "发动机转速传感器",
    "Vehicle Speed Sensor": "车速传感器",
    "Engine": "发动机",
    "Vehicle": "车辆",
    "Speed": "转速",
    "Target": "目标",
    "Module": "模块",
    "Function": "功能",
    "Signal": "信号",
    "Power": "功率",
    "Loop": "回路",
    "Fuel": "燃油",
    "Data": "数据",
    "File": "文件",
    "Unit": "单元",
    "Electronic": "电子",
    "Electric": "电动",
    "Hydraulic": "液压",
    "Mechanical": "机械",
    "Pneumatic": "气动",
    "Automatic": "自动",
    "Manual": "手动",

    # ══════════════════════════════════════════════════════
    #  材料与化学（来源：爱词霸英汉化学大词典+英汉冶金大词典）
    # ══════════════════════════════════════════════════════
    "Aluminum": "铝",
    "Aluminium": "铝",
    "Crankshaft": "曲轴",
    "Camshaft": "凸轮轴",
    "Steel": "钢",
    "Cast Iron": "铸铁",
    "Stainless Steel": "不锈钢",
    "Magnesium": "镁",
    "Titanium": "钛",
    "Copper": "铜",
    "Brass": "黄铜",
    "Bronze": "青铜",
    "Zinc": "锌",
    "Nickel": "镍",
    "Chromium": "铬",
    "Manganese": "锰",
    "Silicon": "硅",
    "Carbon Fiber": "碳纤维",
    "Composite Material": "复合材料",
    "Ceramic": "陶瓷",
    "Polymer": "聚合物",
    "Elastomer": "弹性体",
    "Rubber": "橡胶",
    "Plastic": "塑料",
    "Nylon": "尼龙",
    "PTFE": "聚四氟乙烯",
    "Alloy": "合金",
    "Coating": "涂层",
    "Plating": "电镀",
    "Galvanized": "镀锌",
    "Anodized": "阳极氧化",
    "Heat Treatment": "热处理",
    "Quenching": "淬火",
    "Tempering": "回火",
    "Annealing": "退火",
    "Hardness": "硬度",
    "Tensile Strength": "抗拉强度",
    "Yield Strength": "屈服强度",
    "Fatigue Strength": "疲劳强度",
    "Elastic Modulus": "弹性模量",
    "Thermal Conductivity": "导热系数",
    "Thermal Expansion": "热膨胀",
    "Corrosion Resistance": "耐腐蚀性",
    "Wear Resistance": "耐磨性",
    "Friction Coefficient": "摩擦系数",
    "Lubricant": "润滑剂",
    "Grease": "润滑脂",
    "Coolant": "冷却液",
    "Refrigerant": "制冷剂",
    "Brake Fluid": "制动液",
    "Transmission Fluid": "变速箱油",
    "Power Steering Fluid": "动力转向液",
    "AdBlue": "尿素溶液",
    "DEF": "柴油机尾气处理液",
    "Diesel Exhaust Fluid": "柴油机尾气处理液",
    "Ethanol": "乙醇",
    "Methanol": "甲醇",
    "Biodiesel": "生物柴油",
    "Octane": "辛烷值",
    "Cetane": "十六烷值",

    # ══════════════════════════════════════════════════════
    #  法规与排放（来源：CNKI学术术语+爱词霸法学/环境词典）
    # ══════════════════════════════════════════════════════
    "Emission Standard": "排放标准",
    "Euro Norm": "欧标",
    "Euro Standard": "欧标",
    "China Standard": "国标",
    "CARB": "加州空气资源委员会",
    "EPA": "环保署",
    "OBD": "车载诊断",
    "OBD II": "车载诊断第二代",
    "EOBD": "欧洲车载诊断",
    "MIL": "故障指示灯",
    "DTC": "故障码",
    "Diagnostic Trouble Code": "诊断故障码",
    "Readiness Code": "就绪码",
    "Drive Cycle": "驾驶循环",
    "NEDC": "新欧洲驾驶循环",
    "WLTP": "全球轻型车测试规程",
    "WLTC": "全球轻型车测试循环",
    "FTP": "联邦测试规程",
    "RDE": "实际驾驶排放",
    "Real Driving Emissions": "实际驾驶排放",
    "PN": "颗粒物数量",
    "PM": "颗粒物",
    "Particulate Matter": "颗粒物",
    "NOx": "氮氧化物",
    "CO": "一氧化碳",
    "HC": "碳氢化合物",
    "NMHC": "非甲烷碳氢化合物",
    "THC": "总碳氢化合物",
    "CO2": "二氧化碳",
    "Greenhouse Gas": "温室气体",
    "Carbon Footprint": "碳足迹",
    "Zero Emission": "零排放",
    "Low Emission Zone": "低排放区",
    "Evaporative Emission": "蒸发排放",
    "Crankcase Emission": "曲轴箱排放",
    "Tailpipe Emission": "尾气排放",
    "Aftertreatment": "后处理",
    "SCR": "选择性催化还原",
    "Selective Catalytic Reduction": "选择性催化还原",
    "DPF": "柴油颗粒捕集器",
    "Diesel Particulate Filter": "柴油颗粒捕集器",
    "GPF": "汽油颗粒捕集器",
    "Gasoline Particulate Filter": "汽油颗粒捕集器",
    "LNT": "稀燃NOx捕集器",
    "Lean NOx Trap": "稀燃NOx捕集器",
    "DOC": "柴油氧化催化器",
    "Diesel Oxidation Catalyst": "柴油氧化催化器",
    "TWC": "三元催化转化器",
    "Three Way Catalyst": "三元催化转化器",
    "Lambda": "空燃比系数",
    "Stoichiometric": "理论空燃比",
    "Air Fuel Ratio": "空燃比",
    "AFR": "空燃比",
    "Fuel Economy": "燃油经济性",
    "Fuel Consumption": "燃油消耗",
    "CO2 Emission": "二氧化碳排放",

    # ══════════════════════════════════════════════════════
    #  新能源/电动/混动（来源：爱词霸英汉能源大词典）
    # ══════════════════════════════════════════════════════
    "Electric Vehicle": "电动车辆",
    "EV": "电动车辆",
    "BEV": "纯电动车辆",
    "Battery Electric Vehicle": "纯电动车辆",
    "HEV": "混合动力车辆",
    "Hybrid Electric Vehicle": "混合动力车辆",
    "PHEV": "插电式混合动力",
    "Plug-in Hybrid": "插电式混合动力",
    "FCEV": "燃料电池电动车辆",
    "Fuel Cell": "燃料电池",
    "High Voltage Battery": "高压电池",
    "HV Battery": "高压电池",
    "Battery Pack": "电池包",
    "Battery Module": "电池模组",
    "Battery Cell": "电池单体",
    "Lithium Ion": "锂离子",
    "Li-Ion": "锂离子",
    "LFP": "磷酸铁锂",
    "NMC": "镍锰钴",
    "NCA": "镍钴铝",
    "Solid State Battery": "固态电池",
    "SOC": "荷电状态",
    "State of Charge": "荷电状态",
    "SOH": "健康状态",
    "State of Health": "健康状态",
    "SOP": "功率状态",
    "State of Power": "功率状态",
    "BMS": "电池管理系统",
    "Battery Management System": "电池管理系统",
    "Cell Balancing": "电芯均衡",
    "Thermal Management": "热管理",
    "Battery Thermal Management": "电池热管理",
    "Charger": "充电器",
    "On Board Charger": "车载充电机",
    "OBC": "车载充电机",
    "DC Fast Charging": "直流快充",
    "AC Charging": "交流充电",
    "Regenerative Braking": "再生制动",
    "Regen": "再生制动",
    "Motor Generator Unit": "电动发电机单元",
    "MGU": "电动发电机",
    "Inverter": "逆变器",
    "Converter": "变换器",
    "DC DC Converter": "直流变换器",
    "Boost Converter": "升压变换器",
    "Buck Converter": "降压变换器",
    "Power Electronics": "电力电子",
    "IGBT": "绝缘栅双极晶体管",
    "MOSFET": "金属氧化物半导体场效应管",
    "SiC": "碳化硅",
    "GaN": "氮化镓",
    "Traction Motor": "驱动电机",
    "PMSM": "永磁同步电机",
    "Permanent Magnet Synchronous Motor": "永磁同步电机",
    "Induction Motor": "感应电机",
    "SRM": "开关磁阻电机",
    "Switched Reluctance Motor": "开关磁阻电机",
    "Motor Controller": "电机控制器",
    "MCU": "电机控制单元",
    "High Voltage Interlock": "高压互锁",
    "HVIL": "高压互锁回路",
    "Isolation Resistance": "绝缘电阻",
    "Insulation Monitoring": "绝缘监测",
    "Charging Port": "充电口",
    "CCS": "联合充电系统",
    "CHAdeMO": "CHAdeMO快充标准",
    "GB/T": "国标充电标准",
    "Range": "续航里程",
    "Energy Density": "能量密度",
    "Power Density": "功率密度",
    "Range Extender": "增程器",
    "Regenerative Brake Torque": "再生制动扭矩",

    # ══════════════════════════════════════════════════════
    #  ADAS与自动驾驶（来源：专业工程词典+CNKI学术术语）
    # ══════════════════════════════════════════════════════
    "ADAS": "高级驾驶辅助系统",
    "Advanced Driver Assistance": "高级驾驶辅助",
    "ACC": "自适应巡航控制",
    "Adaptive Cruise Control": "自适应巡航控制",
    "AEB": "自动紧急制动",
    "Autonomous Emergency Braking": "自动紧急制动",
    "LKA": "车道保持辅助",
    "Lane Keeping Assist": "车道保持辅助",
    "LDW": "车道偏离预警",
    "Lane Departure Warning": "车道偏离预警",
    "FCW": "前向碰撞预警",
    "Forward Collision Warning": "前向碰撞预警",
    "BSM": "盲区监测",
    "Blind Spot Monitoring": "盲区监测",
    "RCTA": "后方交叉交通预警",
    "Rear Cross Traffic Alert": "后方交叉交通预警",
    "APA": "自动泊车辅助",
    "Automatic Parking Assist": "自动泊车辅助",
    "TSR": "交通标志识别",
    "Traffic Sign Recognition": "交通标志识别",
    "DMS": "驾驶员监控系统",
    "Driver Monitoring System": "驾驶员监控系统",
    "HUD": "抬头显示",
    "Head Up Display": "抬头显示",
    "Surround View": "全景影像",
    "Bird View": "鸟瞰视图",
    "Parking Sensor": "泊车传感器",
    "Ultrasonic Sensor": "超声波传感器",
    "Radar": "雷达",
    "Lidar": "激光雷达",
    "Camera": "摄像头",
    "Front Camera": "前视摄像头",
    "Rear Camera": "后视摄像头",
    "Fisheye Camera": "鱼眼摄像头",
    "Stereo Camera": "双目摄像头",
    "Time of Flight": "飞行时间",
    "Sensor Fusion": "传感器融合",
    "Perception": "感知",
    "Localization": "定位",
    "Path Planning": "路径规划",
    "Motion Planning": "运动规划",
    "Decision Making": "决策",
    "Control Algorithm": "控制算法",
    "V2X": "车联网通信",
    "V2V": "车车通信",
    "V2I": "车路通信",
    "V2P": "车人通信",
    "C-V2X": "蜂窝车联网",
    "DSRC": "专用短程通信",
    "HD Map": "高精地图",
    "High Definition Map": "高精地图",
    "IMU": "惯性测量单元",
    "GNSS": "全球导航卫星系统",
    "RTK": "实时动态定位",
    "Odometry": "里程计",
    "Wheel Odometry": "轮速里程计",
    "Visual Odometry": "视觉里程计",
    "ESC": "电子稳定控制",
    "Electronic Stability Control": "电子稳定控制",
    "TCS": "牵引力控制系统",
    "Traction Control System": "牵引力控制系统",
    "ABS": "防抱死制动系统",
    "Anti-lock Braking System": "防抱死制动系统",
    "EBD": "电子制动力分配",
    "Electronic Brakeforce Distribution": "电子制动力分配",
    "EBA": "紧急制动辅助",
    "Emergency Brake Assist": "紧急制动辅助",
    "HBA": "液压制动辅助",
    "Hydraulic Brake Assist": "液压制动辅助",
    "HHC": "坡道起步辅助",
    "Hill Hold Control": "坡道起步辅助",
    "HDC": "陡坡缓降控制",
    "Hill Descent Control": "陡坡缓降控制",
    "ESP": "电子稳定程序",

    # ══════════════════════════════════════════════════════
    #  诊断与通信协议（来源：爱词霸英汉计算机大词典）
    # ══════════════════════════════════════════════════════
    "CAN": "控制器局域网",
    "Controller Area Network": "控制器局域网",
    "CAN FD": "CAN灵活数据速率",
    "CAN Flexible Data Rate": "CAN灵活数据速率",
    "LIN": "局域互联网络",
    "Local Interconnect Network": "局域互联网络",
    "FlexRay": "FlexRay总线",
    "MOST": "媒体导向系统传输",
    "Ethernet": "以太网",
    "Automotive Ethernet": "车载以太网",
    "SENT": "单边半字节传输",
    "PSI5": "外设传感器接口5",
    "SPI": "串行外设接口",
    "I2C": "集成电路总线",
    "UART": "通用异步收发传输器",
    "J1939": "SAE J1939协议",
    "J1979": "SAE J1979诊断协议",
    "ISO 14229": "统一诊断服务标准",
    "ISO 14230": "KWP2000诊断协议",
    "ISO 15765": "CAN诊断协议",
    "UDS": "统一诊断服务",
    "Unified Diagnostic Services": "统一诊断服务",
    "KWP2000": "关键字协议2000",
    "XCP": "通用标定协议",
    "CCP": "CAN标定协议",
    "CAN Calibration Protocol": "CAN标定协议",
    "ASAM": "自动化与测量系统标准化协会",
    "ASAP2": "ASAM MCD-2 MC标准",
    "ASAP3": "ASAM MCD-3 MC标准",
    "DID": "数据标识符",
    "Data Identifier": "数据标识符",
    "RID": "例行控制标识符",
    "Routine Identifier": "例行控制标识符",
    "DTC Status": "故障码状态",
    "Freeze Frame": "冻结帧",
    "Snapshot": "快照",
    "Session": "会话",
    "Security Access": "安全访问",
    "Seed Key": "种子密钥",
    "Response On Event": "事件响应",
    "Periodic Transmission": "周期发送",
    "Gateway": "网关",
    "Router": "路由器",
    "Frame": "帧",
    "Message": "报文",
    "Signal": "信号",
    "PDU": "协议数据单元",
    "Checksum": "校验和",
    "CRC": "循环冗余校验",
    "Rolling Counter": "滚动计数器",
    "Alive Counter": "存活计数器",
    "Timeout": "超时",
    "Watchdog": "看门狗",
    "Reset": "复位",
    "Wakeup": "唤醒",
    "Sleep": "休眠",
    "Standby": "待机",
    "Bootloader": "引导加载程序",
    "Flash Programming": "刷写",
    "Reprogramming": "重新编程",
    "VIN": "车辆识别码",
    "ECU Address": "ECU地址",
    "Node": "节点",
    "Topology": "拓扑",
    "Bus Off": "总线关闭",
    "Error Frame": "错误帧",
    "Acknowledge": "应答",
    "Arbitration": "仲裁",
    "Bit Timing": "位定时",
    "Sample Point": "采样点",
    "Baudrate": "波特率",
    "Termination Resistor": "终端电阻",
    "Shield": "屏蔽",
    "Twisted Pair": "双绞线",

    # ══════════════════════════════════════════════════════
    #  NVH与振动噪声（来源：英汉机械大词典）
    # ══════════════════════════════════════════════════════
    "NVH": "噪声振动与声振粗糙度",
    "Noise Vibration Harshness": "噪声振动与声振粗糙度",
    "Vibration": "振动",
    "Noise": "噪声",
    "Acoustic": "声学",
    "Acoustics": "声学",
    "Sound Pressure": "声压",
    "Sound Level": "声级",
    "Decibel": "分贝",
    "dB": "分贝",
    "Frequency": "频率",
    "Amplitude": "振幅",
    "Resonance": "共振",
    "Resonant Frequency": "共振频率",
    "Natural Frequency": "固有频率",
    "Mode Shape": "振型",
    "Modal Analysis": "模态分析",
    "Damping": "阻尼",
    "Damping Ratio": "阻尼比",
    "Isolation": "隔振",
    "Vibration Isolation": "隔振",
    "Absorption": "吸声",
    "Sound Absorption": "吸声",
    "Transmission Loss": "传递损失",
    "Insertion Loss": "插入损失",
    "Engine Mount": "发动机悬置",
    "Suspension Mount": "悬架衬套",
    "Bushing": "衬套",
    "Isolator": "隔振器",
    "Tuned Mass Damper": "调谐质量阻尼器",
    "Balance Shaft": "平衡轴",
    "Counterbalance": "平衡",
    "Imbalance": "不平衡",
    "Runout": "跳动",
    "Eccentricity": "偏心",
    "Orders": "阶次",
    "Order Analysis": "阶次分析",
    "FFT": "快速傅里叶变换",
    "Fast Fourier Transform": "快速傅里叶变换",
    "Spectrum": "频谱",
    "Spectrogram": "频谱图",
    "Waterfall Plot": "瀑布图",
    "Colormap": "彩图",
    "Transfer Path Analysis": "传递路径分析",
    "TPA": "传递路径分析",
    "Source Path Receiver": "源-路径-接收者",
    "Harshness": "声振粗糙度",
    "Buzz Squeak Rattle": "异响",
    "BSR": "异响",
    "Rattle": "咔嗒声",
    "Squeak": "吱吱声",
    "Boom": "轰鸣声",
    "Whine": "啸叫声",
    "Whistle": "吹哨声",
    "Hiss": "嘶嘶声",
    "Groan": "嘎吱声",
    "Moan": "嗡嗡声",
    "Engine Order": "发动机阶次",
    "Firing Order": "点火阶次",
    "Torsional Vibration": "扭转振动",
    "Bending Vibration": "弯曲振动",
    "Axial Vibration": "轴向振动",
    "Radial Vibration": "径向振动",
    "Powertrain": "动力总成",
    "Driveline": "传动系",
    "Drivetrain": "传动系",

    # ══════════════════════════════════════════════════════
    #  电气与电子系统
    # ══════════════════════════════════════════════════════
    "Wiring Harness": "线束",
    "Harness": "线束",
    "Connector": "连接器",
    "Terminal": "端子",
    "Pin": "引脚",
    "Socket": "插座",
    "Plug": "插头",
    "Relay": "继电器",
    "Fuse": "保险丝",
    "Fuse Box": "保险丝盒",
    "Circuit Breaker": "断路器",
    "Ground": "接地",
    "Earth": "接地",
    "Power Supply": "电源",
    "Voltage Supply": "电压供应",
    "Power Distribution": "配电",
    "Alternator": "发电机",
    "Generator": "发电机",
    "Starter": "起动机",
    "Starter Motor": "起动机",
    "Ignition Coil": "点火线圈",
    "Spark Plug": "火花塞",
    "Glow Plug": "预热塞",
    "Actuator": "执行器",
    "Solenoid": "电磁阀",
    "Relay": "继电器",
    "Hall Sensor": "霍尔传感器",
    "Inductive Sensor": "电感式传感器",
    "Capacitive Sensor": "电容式传感器",
    "Resistive Sensor": "电阻式传感器",
    "Strain Gauge": "应变片",
    "Piezo": "压电",
    "Piezoelectric": "压电",
    "MEMS": "微机电系统",
    "ADC": "模数转换器",
    "Analog Digital Converter": "模数转换器",
    "DAC": "数模转换器",
    "Digital Analog Converter": "数模转换器",
    "PWM": "脉宽调制",
    "Pulse Width Modulation": "脉宽调制",
    "Duty Cycle": "占空比",
    "Frequency": "频率",
    "PWM Frequency": "PWM频率",
    "H-Bridge": "H桥",
    "Half Bridge": "半桥",
    "Full Bridge": "全桥",
    "Current Sense": "电流检测",
    "Voltage Sense": "电压检测",
    "Overcurrent": "过流",
    "Overvoltage": "过压",
    "Undervoltage": "欠压",
    "Short Circuit": "短路",
    "Open Circuit": "开路",
    "Open Load": "开路负载",
    "Load Dump": "抛负载",
    "Reverse Polarity": "反极性",
    "ESD": "静电放电",
    "EMC": "电磁兼容",
    "EMI": "电磁干扰",
    "Electromagnetic Compatibility": "电磁兼容",
    "Electromagnetic Interference": "电磁干扰",
    "Radiated Emission": "辐射发射",
    "Conducted Emission": "传导发射",
    "Radiated Immunity": "辐射抗扰",
    "Conducted Immunity": "传导抗扰",
    "ESD Protection": "静电保护",
    "Filter": "滤波器",
    "Low Pass Filter": "低通滤波器",
    "High Pass Filter": "高通滤波器",
    "Band Pass Filter": "带通滤波器",
    "RC Filter": "RC滤波器",
    "Decoupling": "去耦",
    "Bypass": "旁路",
    "Ferrite": "铁氧体",
    "Shielding": "屏蔽",
    "PCB": "印刷电路板",
    "Printed Circuit Board": "印刷电路板",

    # ══════════════════════════════════════════════════════
    #  安全系统（来源：爱词霸英汉消防大词典+工程规范）
    # ══════════════════════════════════════════════════════
    "Airbag": "安全气囊",
    "Seatbelt": "安全带",
    "Seat Belt": "安全带",
    "Pretensioner": "预紧器",
    "Load Limiter": "限力器",
    "Rollover": "翻滚",
    "Rollover Detection": "翻滚检测",
    "Side Impact": "侧面碰撞",
    "Frontal Impact": "正面碰撞",
    "Rear Impact": "追尾碰撞",
    "Offset Crash": "偏置碰撞",
    "Crash Test": "碰撞测试",
    "NCAP": "新车评价规程",
    "C-NCAP": "中国新车评价规程",
    "Euro NCAP": "欧洲新车评价规程",
    "Passive Safety": "被动安全",
    "Active Safety": "主动安全",
    "Functional Safety": "功能安全",
    "ISO 26262": "功能安全标准",
    "ASIL": "汽车安全完整性等级",
    "ASIL A": "安全完整性等级A",
    "ASIL B": "安全完整性等级B",
    "ASIL C": "安全完整性等级C",
    "ASIL D": "安全完整性等级D",
    "HARA": "危害分析与风险评估",
    "Safety Goal": "安全目标",
    "Safety Requirement": "安全要求",
    "Safety Mechanism": "安全机制",
    "Fault": "故障",
    "Failure": "失效",
    "Single Point Fault": "单点故障",
    "Latent Fault": "潜伏故障",
    "Safe State": "安全状态",
    "Degradation": "降级",
    "Fail Safe": "失效安全",
    "Fail Operational": "失效可运行",
    "Redundancy": "冗余",
    "Dual Core": "双核",
    "Lockstep": "锁步",
    "ECC": "纠错码",
    "Error Correcting Code": "纠错码",
    "Memory Protection": "内存保护",
    "MPU": "内存保护单元",
    "ECC Error": "ECC错误",
    "SBC": "系统基础芯片",
    "Power On Reset": "上电复位",
    "BIST": "内建自测试",
    "FIT": "失效率单位",
    "MTTF": "平均失效时间",
    "MTBF": "平均无故障时间",
    "FMEA": "失效模式与影响分析",
    "FTA": "故障树分析",
    "DFA": "依赖失效分析",
    "FMEDA": "失效模式影响与诊断分析",
    "SPFM": "单点故障度量",
    "LFM": "潜伏故障度量",
    "PMHF": "随机硬件失效概率度量",

    # ══════════════════════════════════════════════════════
    #  测试与标定专用术语
    # ══════════════════════════════════════════════════════
    "Test Bench": "测试台架",
    "Dynamometer": "测功机",
    "Dyno": "测功机",
    "Chassis Dyno": "底盘测功机",
    "Engine Dyno": "发动机测功机",
    "Roller Bench": "转鼓台架",
    "HIL": "硬件在环",
    "Hardware in the Loop": "硬件在环",
    "SIL": "软件在环",
    "Software in the Loop": "软件在环",
    "MIL": "模型在环",
    "Model in the Loop": "模型在环",
    "PIL": "处理器在环",
    "Processor in the Loop": "处理器在环",
    "VIL": "车辆在环",
    "Vehicle in the Loop": "车辆在环",
    "Rapid Prototyping": "快速原型",
    "RCP": "快速控制原型",
    "Bypass": "旁路",
    "Fullpass": "全通路",
    "Measurement": "测量",
    "Acquisition": "采集",
    "DAQ": "数据采集",
    "Data Acquisition": "数据采集",
    "Sampling Rate": "采样率",
    "Sampling Time": "采样时间",
    "Resolution": "分辨率",
    "Accuracy": "精度",
    "Precision": "精密度",
    "Repeatability": "重复性",
    "Reproducibility": "复现性",
    "Hysteresis": "迟滞",
    "Linearity": "线性度",
    "Nonlinearity": "非线性度",
    "Offset": "偏移",
    "Drift": "漂移",
    "Temperature Drift": "温度漂移",
    "Zero Drift": "零点漂移",
    "Gain Error": "增益误差",
    "Quantization Error": "量化误差",
    "Noise Floor": "本底噪声",
    "SNR": "信噪比",
    "Signal to Noise Ratio": "信噪比",
    "THD": "总谐波失真",
    "Total Harmonic Distortion": "总谐波失真",
    "Rise Time": "上升时间",
    "Fall Time": "下降时间",
    "Settling Time": "稳定时间",
    "Response Time": "响应时间",
    "Latency": "延迟",
    "Jitter": "抖动",
    "Phase Shift": "相移",
    "Phase Delay": "相位延迟",
    "Group Delay": "群延迟",
    "Calibration Factor": "标定系数",
    "Correction Factor": "修正系数",
    "Scale Factor": "比例因子",
    "Scaling": "缩放",
    "Offset Correction": "偏移修正",
    "Gain Correction": "增益修正",
    "Calibration Curve": "标定曲线",
    "Lookup Table": "查表",
    "LUT": "查找表",
    "Interpolation": "插值",
    "Linear Interpolation": "线性插值",
    "Extrapolation": "外推",
    "Map": "脉谱图",
    "Map Data": "脉谱数据",
    "Curve": "曲线",
    "Characteristic Curve": "特性曲线",
    "Operating Point": "工作点",
    "Setpoint": "设定值",
    "Set Point": "设定值",
    "Actual Value": "实际值",
    "Nominal Value": "标称值",
    "Target Value": "目标值",
    "Limit Value": "限值",
    "Threshold": "阈值",
    "Upper Limit": "上限",
    "Lower Limit": "下限",
    "Deadband": "死区",
    "Hysteresis Band": "迟滞带",
    "Tolerance": "公差",
    "Tolerance Band": "公差带",
    "Ramp": "斜坡",
    "Ramp Rate": "斜坡速率",
    "Step": "阶跃",
    "Step Response": "阶跃响应",
    "Impulse Response": "冲激响应",
    "Transfer Function": "传递函数",
    "Bode Plot": "波特图",
    "Nyquist Plot": "奈奎斯特图",
    "Stability": "稳定性",
    "Robustness": "鲁棒性",
    "Sensitivity": "灵敏度",
    "Controllability": "可控性",
    "Observability": "可观测性",
    "PID": "比例积分微分",
    "PID Controller": "PID控制器",
    "PI Controller": "PI控制器",
    "PD Controller": "PD控制器",
    "Proportional Gain": "比例增益",
    "Integral Gain": "积分增益",
    "Derivative Gain": "微分增益",
    "Feedforward": "前馈",
    "Feedback": "反馈",
    "Closed Loop Control": "闭环控制",
    "Open Loop Control": "开环控制",
    "Adaptive Control": "自适应控制",
    "Model Predictive Control": "模型预测控制",
    "MPC": "模型预测控制",
    "State Observer": "状态观测器",
    "Kalman Filter": "卡尔曼滤波器",
    "Extended Kalman Filter": "扩展卡尔曼滤波器",
    "EKF": "扩展卡尔曼滤波器",
    "UKF": "无迹卡尔曼滤波器",
}

# ══════════════════════════════════════════════════════════
#  德语汽车术语 → 中文（A2L文件常见德语词汇）
# ══════════════════════════════════════════════════════════


GERMAN_GLOSSARY = {
    "Motordrehzahl": "发动机转速",
    "Fahrzeuggeschwindigkeit": "车速",
    "Kühlmitteltemperatur": "冷却液温度",
    "Ansauglufttemperatur": "进气温度",
    "Umgebungstemperatur": "环境温度",
    "Umgebungsdruck": "环境压力",
    "Saugrohrdruck": "进气歧管压力",
    "Ladedruckregelung": "增压压力控制",
    "Ladedruck": "增压压力",
    "Kraftstoffdruck": "燃油压力",
    "Öldruck": "机油压力",
    "Öltemperatur": "机油温度",
    "Kraftstofftemperatur": "燃油温度",
    "Batteriespannung": "电池电压",
    "Drosselklappenstellung": "节气门位置",
    "Gaspedalstellung": "油门踏板位置",
    "Bremspedalstellung": "制动踏板位置",
    "Lenkwinkel": "转向角度",
    "Gierrate": "横摆角速度",
    "Luftmassenstrom": "空气质量流量",
    "Kraftstoffmassenstrom": "燃油质量流量",
    "Einspritzmenge": "喷油量",
    "Einspritzzeitpunkt": "喷油正时",
    "Zündzeitpunkt": "点火正时",
    "Zündwinkel": "点火提前角",
    "Schließwinkel": "闭合角",
    "Lambdawert": "Lambda值",
    "Lambdasollwert": "Lambda目标值",
    "Lambdaregelung": "Lambda控制",
    "Lambdasonde": "氧传感器",
    "Abgastemperatur": "排气温度",
    "Abgasdruck": "排气压力",
    "Abgasrückführung": "废气再循环",
    "AGR Ventil": "EGR阀",
    "AGR Rate": "EGR率",
    "Turboladerdrehzahl": "涡轮增压器转速",
    "Raildruck": "共轨压力",
    "Motormoment": "发动机扭矩",
    "Motorlast": "发动机负荷",
    "Fahrerwunschmoment": "驾驶员需求扭矩",
    "Reibmoment": "摩擦扭矩",
    "Leerlaufdrehzahl": "怠速转速",
    "Leerlaufregelung": "怠速控制",
    "Klopfregelung": "爆震控制",
    "Klopfsensor": "爆震传感器",
    "Kurbelwellenposition": "曲轴位置",
    "Kurbelwelle": "曲轴",
    "Nockenwellenposition": "凸轮轴位置",
    "Nockenwellenphase": "凸轮轴相位",
    "Variable Ventilsteuerung": "可变气门正时",
    "Einspritzdauer": "喷油脉宽",
    "Schubabschaltung": "减速断油",
    "Abgasnachbehandlung": "排气后处理",
    "Katalysatortemperatur": "催化器温度",
    "Voreinspritzung": "预喷",
    "Haupteinspritzung": "主喷",
    "Nacheinspritzung": "后喷",
    "Motorsteuergerät": "发动机控制单元",
    "Getriebesteuergerät": "变速箱控制单元",
    "Applikation": "标定",
    "Messwert": "测量量",
    "Kennwert": "特性参数",
    "Kennfeld": "特性图",
    "Kennlinie": "特性曲线",
    "Umrechnungsvorschrift": "计算方法",
    "Achse": "轴",
    "Auflösung": "分辨率",
    "Genauigkeit": "精度",
    "Bereich": "范围",
    "Schwellwert": "阈值",
    "Hysterese": "迟滞",
    "Filterkoeffizient": "滤波系数",
    "Zeitkonstante": "时间常数",
    "Totzeit": "死区时间",
    "Verzögerung": "延迟",
    "Anreicherung": "加浓",
    "Abmagerung": "减稀",
    "Gemischregelung": "混合气控制",
    "Zündungsregelung": "点火控制",
    "Füllungserfassung": "充气检测",
    "Saugrohr": "进气歧管",
    "Abgaskrümmer": "排气歧管",
    "Ventilhub": "气门升程",
    "Ventilüberschneidung": "气门重叠",
    "Ladeluftkühler": "中冷器",
    "Wastegate": "废气旁通阀",
    "Partikelfilter": "颗粒捕集器",
    "Harnstoff": "尿素",
    "Regeneration": "再生",
    "Diagnose": "诊断",
    "Fehlercode": "故障码",
    "Fehlererkennung": "错误检测",
    "Plausibilisierung": "合理性检查",
    "Kurzschluss": "短路",
    "Unterbrechung": "断路",
    "Getriebe": "变速箱",
    "Gang": "档位",
    "Schaltstrategie": "换挡策略",
    "Drehmoment": "扭矩",
    "Drehmomentwandler": "变矩器",
    "Kupplung": "离合器",
    "Hybrid": "混合动力",
    "Elektromotor": "电机",
    "Hochvoltbatterie": "高压电池",
    "Batteriemanagement": "电池管理",
    "Ladezustand": "荷电状态",
    "Rekuperation": "再生制动",
    "Start Stopp": "启停",
    "Bremsdruck": "制动压力",
    "Lenkunterstützung": "转向助力",
    "Fahrwerk": "底盘",
    "Luftfederung": "空气悬架",
    "Dämpfung": "减震",
    "Klimaanlage": "空调",
    "Kältemittel": "冷媒",
    "Verdampfer": "蒸发器",
    "Heizung": "暖风",
    "Gebläse": "鼓风机",
    "CAN Bus": "CAN总线",
    "Netzwerkmanagement": "网络管理",
    "Kalibrierung": "标定",
    "Steuergerät": "控制单元",
    "Sensor": "传感器",
    "Aktuator": "执行器",
    "Ventil": "阀",
    "Pumpe": "泵",
    "Relais": "继电器",
    "Signal": "信号",
    "Regelung": "控制",
    "Aktiv": "激活",
    "Aktivierung": "激活",
    "Deaktivierung": "停用",
    # ── 德语 ASCII 变体（元音转写）──
    "Abgasrueckfuehrung": "废气再循环",
    "AGR Ventil": "EGR阀",
    "AGR Rate": "EGR率",
    "Oeldruck": "机油压力",
    "Oeltemperatur": "机油温度",
    "Kuehlmitteltemperatur": "冷却液温度",
    "Saugrohrdruck": "进气歧管压力",
    "Kraftstoffdruck": "燃油压力",
    "Drosselklappenstellung": "节气门位置",
    "Gaspedalstellung": "油门踏板位置",
    "Bremspedalstellung": "制动踏板位置",
    "Schubabschaltung": "减速断油",
    "Zuendzeitpunkt": "点火正时",
    "Zuendwinkel": "点火提前角",
    "Schliesswinkel": "闭合角",
    "Fuellungserfassung": "充气检测",
    "Abgaskruemmer": "排气歧管",
    "Ueberschneidung": "重叠",
    "Kupplung": "离合器",
    "Geblaese": "鼓风机",
    "Kaeltemittel": "冷媒",
    "Daempfung": "减震",
    "Stoerung": "故障",
    "Eingang": "输入",
    "Ausgang": "输出",
    # ── 德语：ADAS/自动驾驶 ──
    "Spurhalteassistent": "车道保持辅助",
    "Spurverlassenswarnung": "车道偏离预警",
    "Abstandsregeltempomat": "自适应巡航",
    "Notbremsassistent": "紧急制动辅助",
    "Totwinkelassistent": "盲区监测",
    "Verkehrszeichenerkennung": "交通标志识别",
    "Parkassistent": "泊车辅助",
    "Umfeldkamera": "全景摄像头",
    "Frontkamera": "前视摄像头",
    "Radarsensor": "雷达传感器",
    "Ultraschallsensor": "超声波传感器",
    "Fahrerueberwachung": "驾驶员监控",
    # ── 德语：新能源/电动/混动 ──
    "Hochvolt": "高压",
    "Hochvoltsystem": "高压系统",
    "E-Maschine": "电机",
    "Traktionsmotor": "驱动电机",
    "Wechselrichter": "逆变器",
    "Gleichspannungswandler": "直流变换器",
    "Bordladegeraet": "车载充电机",
    "Energiedichte": "能量密度",
    "Reichweite": "续航里程",
    "Ladeinfrastruktur": "充电基础设施",
    "Schnellladung": "快充",
    "Normalladung": "慢充",
    "Zellspannung": "电芯电压",
    "Zelltemperatur": "电芯温度",
    "Isolationswiderstand": "绝缘电阻",
    "Isolationsueberwachung": "绝缘监测",
    "Batteriezelle": "电池单体",
    "Batteriemodul": "电池模组",
    # ── 德语：法规/排放 ──
    "Abgasnorm": "排放标准",
    "Schadstoffemission": "污染物排放",
    "Stickoxid": "氮氧化物",
    "Kohlenmonoxid": "一氧化碳",
    "Kohlenwasserstoff": "碳氢化合物",
    "Kohlendioxid": "二氧化碳",
    "Partikelanzahl": "颗粒数量",
    "Rußpartikelfilter": "颗粒捕集器",
    "Selektive Katalytische Reduktion": "选择性催化还原",
    "Oxidationskatalysator": "氧化催化器",
    "Fahrzyklus": "驾驶循环",
    "Typpruefung": "型式检验",
    # ── 德语：NVH/振动噪声 ──
    "Geraeusch": "噪声",
    "Schwingung": "振动",
    "Koerperschall": "结构噪声",
    "Luftschall": "空气噪声",
    "Eigenfrequenz": "固有频率",
    "Resonanzfrequenz": "共振频率",
    "Resonanz": "共振",
    "Daempfungsmass": "阻尼系数",
    "Motorlager": "发动机悬置",
    "Schwingungsdaempfer": "减振器",
    "Schalldruckpegel": "声压级",
    "Schallleistungspegel": "声功率级",
    "Ordnungsanalyse": "阶次分析",
    "Drehungleichfoermigkeit": "旋转不均匀度",
    "Torsionsschwingung": "扭转振动",
    "Biegeschwingung": "弯曲振动",
    # ── 德语：功能安全 ──
    "Funktionssicherheit": "功能安全",
    "Sicherheitsziel": "安全目标",
    "Sicherheitsmechanismus": "安全机制",
    "Sicherheitsanforderung": "安全要求",
    "Einzelfehler": "单点故障",
    "Mehrfachfehler": "多点故障",
    "Latenter Fehler": "潜伏故障",
    "Sicherer Zustand": "安全状态",
    "Fehlertoleranz": "容错",
    "Ausfallrate": "失效率",
    "Risikobewertung": "风险评估",
    "Gefaehrdungsanalyse": "危害分析",
    "Degradationsmodus": "降级模式",
    "Notlauf": "跛行模式",
    # ── 德语：测试台架 ──
    "Pruefstand": "测试台架",
    "Motorpruefstand": "发动机台架",
    "Rollenpruefstand": "转鼓台架",
    "Komponentenpruefstand": "部件台架",
    "Dauerlauf": "耐久试验",
    "Kaltstart": "冷启动",
    "Warmstart": "热启动",
    "Heissstart": "热态启动",
    "Leistungsmessung": "功率测量",
    "Verbrauchsmessung": "油耗测量",
    "Emissionsmessung": "排放测量",
    # ── 德语：诊断 ──
    "Fehlerspeicher": "故障存储器",
    "Fehlereintrag": "故障条目",
    "Fehlerpfad": "故障路径",
    "Fehlerstatus": "故障状态",
    "Umweltbedingung": "环境条件",
    "Standbild": "冻结帧",
    "Diagnoseprotokoll": "诊断协议",
    "Diagnoseadresse": "诊断地址",
    "Sicherheitszugriff": "安全访问",
    "Programmierung": "编程",
    "Flashvorgang": "刷写",
    "Bootloaderaktivierung": "引导加载激活",
    # ── 德语：通信 ──
    "Buslast": "总线负载",
    "Botschaft": "报文",
    "Signalnummer": "信号编号",
    "Signalgruppe": "信号组",
    "Zykluszeit": "循环时间",
    "Sendezyklus": "发送周期",
    "Empfang": "接收",
    "Senden": "发送",
    "Initialisierung": "初始化",
    "Konfiguration": "配置",
    "Synchronisation": "同步",
    # ── 德语材料 ──
    "Werkstoff": "材料",
    "Aluminium": "铝",
    "Edelstahl": "不锈钢",
    "Gusseisen": "铸铁",
    "Kunststoff": "塑料",
    "Glasfaser": "玻璃纤维",
    "Kohlefaser": "碳纤维",
    "Legierung": "合金",
    "Beschichtung": "涂层",
    "Oberflaeche": "表面",
    "Korrosion": "腐蚀",
    "Verschleiss": "磨损",
    # ── 德语：底盘/制动/转向 ──
    "Fahrdynamikregelung": "车辆动态控制",
    "Antriebsschlupfregelung": "驱动防滑控制",
    "Bremsassistent": "制动辅助",
    "Bremskraftverstaerker": "制动助力器",
    "Feststellbremse": "驻车制动",
    "Lenkgetriebe": "转向机",
    "Lenksaeule": "转向柱",
    "Zwischenwelle": "中间轴",
    "Achsuebersetzung": "主减速比",
    "Differentialsperre": "差速锁",
    "Allradantrieb": "全轮驱动",
    "Vorderachse": "前轴",
    "Hinterachse": "后轴",
    "Sturz": "外倾角",
    "Spur": "前束",
    "Nachlauf": "主销后倾",
    "Spreizung": "主销内倾",
    # ── 德语ASCII变体补充 ──
    "Spurhalteassistent": "车道保持辅助",
    "Spurverlassenswarnung": "车道偏离预警",
    "Abstandsregeltempomat": "自适应巡航",
    "Notbremsassistent": "紧急制动辅助",
    "Totwinkelassistent": "盲区监测",
    "Verkehrszeichenerkennung": "交通标志识别",
    "Parkassistent": "泊车辅助",
    "Umfeldkamera": "全景摄像头",
    "Isolationswiderstand": "绝缘电阻",
    "Isolationsueberwachung": "绝缘监测",
    "Stickoxid": "氮氧化物",
    "Kohlenmonoxid": "一氧化碳",
    "Kohlenwasserstoff": "碳氢化合物",
    "Kohlendioxid": "二氧化碳",
    "Schadstoffemission": "污染物排放",
    "Pruefstand": "测试台架",
    "Dauerlauf": "耐久试验",
    "Leistungsmessung": "功率测量",
    "Verbrauchsmessung": "油耗测量",
    "Emissionsmessung": "排放测量",
    "Fehlerspeicher": "故障存储器",
    "Fehlereintrag": "故障条目",
    "Fehlerpfad": "故障路径",
    "Fehlerstatus": "故障状态",
    "Umweltbedingung": "环境条件",
    "Diagnoseprotokoll": "诊断协议",
    "Diagnoseadresse": "诊断地址",
    "Sicherheitszugriff": "安全访问",
    "Buslast": "总线负载",
    "Sendezyklus": "发送周期",
    "Zykluszeit": "循环时间",
    "Werkstoff": "材料",
    "Edelstahl": "不锈钢",
    "Gusseisen": "铸铁",
    "Kunststoff": "塑料",
    "Glasfaser": "玻璃纤维",
    "Kohlefaser": "碳纤维",
    "Legierung": "合金",
    "Beschichtung": "涂层",
    "Oberflaeche": "表面",
    "Korrosion": "腐蚀",
    "Verschleiss": "磨损",
    "Fahrdynamikregelung": "车辆动态控制",
    "Antriebsschlupfregelung": "驱动防滑控制",
    "Bremsassistent": "制动辅助",
    "Bremskraftverstaerker": "制动助力器",
    "Feststellbremse": "驻车制动",
    "Lenkgetriebe": "转向机",
    "Lenksaeule": "转向柱",
    "Zwischenwelle": "中间轴",
    "Achsuebersetzung": "主减速比",
    "Allradantrieb": "全轮驱动",
    "Vorderachse": "前轴",
    "Hinterachse": "后轴",
    "Oberflaeche": "表面",
}

# ════════════════════════════════════════════════════════
#  逐词智能翻译关键词库 — 补足词典精确匹配覆盖不到的短语
# ════════════════════════════════════════════════════════
SMART_KEYWORDS = {
    # ── 发动机/排气/进气 ──
    "exhaust": "排气", "induction": "进气", "cooling": "冷却", "heating": "加热",
    "brick": "砖块/载体", "catalyst": "催化剂", "compressor": "压缩机",
    "downstream": "下游", "upstream": "上游", "ambient": "环境",
    "ambient air": "环境空气", "thermal": "热", "capacity": "容量/能力",
    "convection": "对流", "diameter": "直径",
    "surface": "表面", "shut off": "关闭", "shut": "关闭",
    "per cylinder": "每缸", "per hour": "每小时",
    "mass flow": "质量流量", "volume flow": "体积流量",
    "specific heat": "比热", "heat capacity": "热容量", "molar weight": "摩尔质量",
    "dosing": "喷射/计量", "demand": "需求",
    "exhaust gas mass flow": "排气质量流量",
    "filtered exhaust gas mass flow": "滤波后排气质量流量",
    "exhaust gas volume flow": "排气体积流量",
    "filtered exhaust gas volume flow": "滤波后排气体积流量",
    "pressure in the induction volume": "进气管路压力",
    "air mass per cylinder": "每缸空气质量",
    "filtered air mass per cylinder": "滤波后每缸空气质量",
    "mass of AFS per hour": "每小时进气质量",
    "induction air temperature": "进气温度",
    "free convection": "自由对流",
    "exposed surface of brick to environment": "载体与环境接触表面积",
    "temperature from induction air system temperature field": "进气系统温度场温度",
    "environmental temperature selected from induction air system temperature field": "进气系统温度场环境温度",

    # ── 控制/条件 ──
    "A/C": "空调", "Ctrl": "控制", "Ctrl shut off": "控制关闭",
    "filtered": "滤波/过滤后", "unfiltered": "未滤波", "raw": "原始",
    "limitation": "限制", "position": "位置", "desired": "期望/目标",
    "boundary": "边界", "condition": "条件", "enabling": "使能",
    "disabling": "禁用", "mask": "掩码", "overwrite": "覆盖",
    "diagnosis": "诊断", "flag": "标记/标志位",
    "switch": "开关/选择", "selector": "选择器", "selection": "选择",
    "currently": "当前", "stored": "存储的", "environmental": "环境",
    "measuring point": "测量点", "application tool": "标定工具",
    "substate": "子状态", "afterrun": "后运行", "emptying": "排空",
    "statusbyte": "状态字节", "inhibition": "抑制",
    "inhibition flag": "抑制标志",
    "absolute": "绝对", "difference": "差值/差异",
    "temperature difference": "温差",
    "temperature downstream": "下游温度",
    "software switch": "软件开关", "operation modes": "运行模式",
    "selectable options": "可选项", "codeword": "编码字/配置字",
    "AC cooling demand": "空调制冷需求",
    "relative AC cooling demand": "空调相对制冷需求",
    "adjust release": "调节释放", "activity": "活性/活动",
    "enviroment": "环境", "undelay": "取消延迟",
    "pro longing": "延长", "pre drive": "预驱动",
    "deactivation": "去激活", "initialisation": "初始化",
    "steep input": "陡变输入",
    "this is sw-calprm": "（标定参数）",
    "this is sw-variable": "（软件变量）",

    # ── 管路/几何 ──
    "of the tube": "管路", "tube length": "管路长度",
    "tube diameter": "管路直径", "tube surface": "管路表面积",
    "of the brick": "载体", "mass of the brick": "载体质量",

    # ── 油门踏板 ──
    "acceleration pedal position": "油门踏板位置",
    "acceleration pedal raw1 voltage": "油门踏板原始电压1",
    "acceleration pedal raw2 voltage": "油门踏板原始电压2",
    "link operator switches": "逻辑运算符开关",

    # ── 环境/温度 ──
    "maximal environment temperature": "最高环境温度",
    "minimal environment temperature": "最低环境温度",
    "zero flow for EGR": "EGR零流量",
    "selector for input temperature of HC load model": "HC负载模型输入温度选择器",
    "selector for temperature element": "温度场元素选择器",

    # ── 数学/计算 ──
    "beta": "贝塔", "array": "数组", "index": "索引",
    "exponent": "指数", "coordinate": "坐标", "inverse": "反向/倒数",

    # ── 汽车术语 ──
    "idle": "怠速", "throttle": "节气门", "valve": "阀",
    "EGR": "废气再循环", "HC": "碳氢化合物", "NH3": "氨气",
    "NOx": "氮氧化物", "PM": "颗粒物", "SCR": "选择性催化还原",
    "DPF": "颗粒捕集器", "DOC": "氧化催化器", "LNT": "稀燃NOx捕集器",
    "ECU": "电控单元", "OBD": "车载诊断",
    "CAN": "控制器局域网", "LIN": "局域互联网络",
    "PWM": "脉宽调制", "ADC": "模数转换",
    "DAC": "数模转换", "EEPROM": "电可擦除只读存储器",
    "RAM": "随机存取存储器", "ROM": "只读存储器",

    # ── AUTOSAR 软件架构 ──
    "ASW": "应用软件", "BSW": "基础软件", "RTE": "运行时环境",
    "Dem": "诊断事件管理", "NvM": "非易失性存储器管理",
    "ComM": "通信管理", "EcuM": "ECU状态管理",
    "BswM": "基础软件模式管理", "WdgM": "看门狗管理",

    # ── PM 传感器 ──
    "PM sensor": "颗粒物传感器",
    "length": "长度",
}
